# This is a basic workflow to help you get started with Actions

name: CI creation issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  issues:
    types: [opened]
jobs:
  issue-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: my new issue
